# Generated by Django 4.2.16 on 2026-08-21 12:09

import Driver.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Operations Manager', 'Operations Manager'), ('Support Lead', 'Support Lead'), ('Finance Admin', 'Finance Admin')], default='Operations Manager', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_notifications',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(default='DRIVER', max_length=20)),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usage_limit', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Disabled', 'Disabled')], default='Active', max_length=20)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True, unique=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle_category', models.CharField(blank=True, choices=[('Bike', 'Bike'), ('Auto', 'Auto'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('EV', 'EV')], max_length=20, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('registration_certificate', models.CharField(blank=True, help_text='Vehicle Registration Certificate (RC) Number', max_length=50, null=True, unique=True)),
                ('registration_certificate_image', models.ImageField(blank=True, help_text='Upload Registration Certificate image', null=True, upload_to='driver_documents/rc/')),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_online', models.BooleanField(db_index=True, default=False)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_category', models.CharField(max_length=30)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dropoff_address', models.TextField()),
                ('dropoff_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dropoff_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('driver_enroute', 'Driver Enroute'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Wallet', 'Wallet'), ('Card', 'Card')], default='UPI', max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('otp_code', models.CharField(default='1234', max_length=6)),
                ('sos_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='Driver.driver')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'riders',
            },
        ),
        migrations.CreateModel(
            name='SurgeZone',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('center_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('auto_surge', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surge_zones',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LICENSE', 'Driving License'), ('REGISTRATION', 'Vehicle Registration (RC)'), ('INSURANCE', 'Vehicle Insurance'), ('PERMIT', 'Commercial Permit')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Driver.driver')),
            ],
            options={
                'db_table': 'vehicle_documents',
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('alert_code', models.CharField(db_index=True, max_length=100)),
                ('rider_name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE_EMERGENCY', 'Active Emergency'), ('DISPATCHED', 'Dispatched'), ('RESOLVED_FALSE_ALARM', 'Resolved (False Alarm)'), ('RESOLVED_POLICE_NOTIFIED', 'Resolved (Police Notified)')], default='ACTIVE_EMERGENCY', max_length=30)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='Driver.ride')),
            ],
            options={
                'db_table': 'sos_alerts',
            },
        ),
        migrations.AddField(
            model_name='ride',
            name='rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='Driver.rider'),
        ),
        migrations.CreateModel(
            name='EarningsTransaction',
            fields=[
                ('id', models.CharField(default=Driver.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('PAYOUT', 'Payout')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_transactions', to='Driver.driver')),
            ],
            options={
                'db_table': 'earnings_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_online', 'kyc_status'], name='drivers_is_onli_da7aab_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['registration_certificate'], name='drivers_registr_816b16_idx'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='Driver.ride'),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Driver.driver'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', 'status'], name='rides_rider_i_6aa1b3_idx'),
        ),
    ]
