# Generated by Django 4.2.16 on 2026-08-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
