# Generated by Django 6.1 on 2026-08-13 06:57

import django.db.models.deletion
import rides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Operations Manager', 'Operations Manager'), ('Support Lead', 'Support Lead'), ('Finance Admin', 'Finance Admin')], default='Operations Manager', max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=150)),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('ip_address', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Flat', 'Flat')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usage_limit', models.IntegerField(default=1000)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Disabled', 'Disabled')], default='Active', max_length=20)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_category', models.CharField(choices=[('Bike', 'Bike'), ('Auto', 'Auto'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('EV', 'EV')], max_length=20)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_number', models.CharField(max_length=50, unique=True)),
                ('kyc_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drivers',
            },
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Blocked', 'Blocked'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'riders',
            },
        ),
        migrations.CreateModel(
            name='SurgeZone',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('zone_name', models.CharField(max_length=100)),
                ('center_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radius_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('auto_surge', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surge_zones',
            },
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('booking_code', models.CharField(max_length=20, unique=True)),
                ('vehicle_category', models.CharField(max_length=30)),
                ('pickup_address', models.TextField()),
                ('pickup_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('dropoff_address', models.TextField()),
                ('dropoff_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('dropoff_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('driver_enroute', 'Driver Enroute'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI'), ('Wallet', 'Wallet'), ('Card', 'Card')], default='UPI', max_length=20)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Refunded', 'Refunded')], default='Pending', max_length=20)),
                ('sos_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rides.driver')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides', to='rides.rider')),
            ],
            options={
                'db_table': 'rides',
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('alert_code', models.CharField(max_length=100)),
                ('rider_name', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE_EMERGENCY', 'Active Emergency'), ('DISPATCHED', 'Dispatched'), ('RESOLVED_FALSE_ALARM', 'Resolved (False Alarm)'), ('RESOLVED_POLICE_NOTIFIED', 'Resolved (Police Notified)')], default='ACTIVE_EMERGENCY', max_length=30)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='rides.ride')),
            ],
            options={
                'db_table': 'sos_alerts',
            },
        ),
    ]
