# Generated by Django 5.2 on 2026-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='booking_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('driver_enroute', 'Driver Enroute'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='rider',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='alert_code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_online', 'kyc_status'], name='drivers_is_onli_da7aab_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['driver', 'status'], name='rides_driver__d736b9_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['rider', 'status'], name='rides_rider_i_6aa1b3_idx'),
        ),
    ]
