# Generated by Django 5.2 on 2026-08-13 09:13

import django.db.models.deletion
import rides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_alter_adminuser_email_alter_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='otp_code',
            field=models.CharField(default='1234', max_length=6),
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rides.driver')),
            ],
            options={
                'db_table': 'app_notifications',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(default='DRIVER', max_length=20)),
                ('message_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='rides.ride')),
            ],
            options={
                'db_table': 'chat_messages',
            },
        ),
        migrations.CreateModel(
            name='EarningsTransaction',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('PAYOUT', 'Payout')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings_transactions', to='rides.driver')),
            ],
            options={
                'db_table': 'earnings_transactions',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.CharField(default=rides.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LICENSE', 'Driving License'), ('REGISTRATION', 'Vehicle Registration (RC)'), ('INSURANCE', 'Vehicle Insurance'), ('PERMIT', 'Commercial Permit')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_image', models.ImageField(blank=True, null=True, upload_to='vehicle_docs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rides.driver')),
            ],
            options={
                'db_table': 'vehicle_documents',
            },
        ),
    ]
