# Generated by Django 5.2 on 2026-08-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_driver_wallet_balance_ride_otp_code_appnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
