# Generated by Django 5.2 on 2026-08-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_driver_otp_code_driver_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_category',
            field=models.CharField(blank=True, choices=[('Bike', 'Bike'), ('Auto', 'Auto'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('EV', 'EV')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
