# Generated by Django 5.2 on 2026-08-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_alter_driver_email_alter_driver_vehicle_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='registration_certificate',
            field=models.CharField(blank=True, help_text='Vehicle Registration Certificate (RC) Number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='registration_certificate_image',
            field=models.ImageField(blank=True, help_text='Upload Registration Certificate image', null=True, upload_to='driver_documents/rc/'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['registration_certificate'], name='drivers_registr_816b16_idx'),
        ),
    ]
